name = "backend"
compatibility_date = "2023-12-01"

[vars]
  DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDE5NWVjMGYtMjA4ZS00OTUxLWEyYTMtODdjODY3MGMyODRlIiwidGVuYW50X2lkIjoiMjQ0MGJlZTYxOGJjMzIxYTRiYjBlNWJkMTJjM2FkNmNhMWM1NmIyZmFiZDdlZDAxYmY5ZGQ0ZjBhNmQxODAyMiIsImludGVybmFsX3NlY3JldCI6IjM5YjRlMjRiLTA0ZTAtNDcxMS1iYmFiLWZiZTE0ZGZlN2E5MyJ9.yr3JVm_Xbodp4heBgkgROwErUt4RzTI4k4arxAPDA2A"
  JWT_SECRET="AkshatSecret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"